using System.Linq;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Content.Shared.Genetics.GeneticsConsole;
using Content.Client.UserInterface.Controls;
using Robust.Client.UserInterface.Controls;
using static Robust.Client.UserInterface.Controls.BoxContainer;
using Content.Shared.Genetics;
using Robust.Client.Graphics;

namespace Content.Client.GeneticsConsole.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class GeneticsConsoleWindow : FancyWindow
    {
        public event Action<BaseButton.ButtonEventArgs>? OnSequenceButtonPressed;
        public event Action<BaseButton.ButtonEventArgs, IndexedButton>? OnRepairButtonPressed;
        public event Action<BaseButton.ButtonEventArgs, IndexedButton>? OnStartActivationButtonPressed;
        public event Action<BaseButton.ButtonEventArgs>? OnActivateButtonPressed;
        public event Action<BaseButton.ButtonEventArgs, IndexedButton>? OnUsedBlockButtonPressed;
        public event Action<BaseButton.ButtonEventArgs, IndexedButton>? OnUnusedBlockButtonPressed;
        public event Action<BaseButton.ButtonEventArgs>? OnCancelActivationButtonPressed;

        public event Action<BaseButton.ButtonEventArgs, FillBasePairButtonPressedMessage>? OnFillBasePairButtonPressed;

        private List<Gene> _lastGeneSequence = new List<Gene>(); //TODO: this is bad
        private bool _geneDirty = false;

        private int _prevUsedBlockCnt = 0;
        private int _prevUnusedBlockCnt = 0;
        private bool _modalOpen = false;

        private int _targetDNABlockIndex = 0;
        private int _targetPairIndex = 0;
        private bool _targetBaseTop = false;

        private static readonly Vector2 BlockSize = new(15, 15);


        private static readonly Dictionary<Base, Color> BaseToColor = new Dictionary<Base, Color>
            {
                { Base.A, Color.FromHex("#092142") },
                { Base.T, Color.FromHex("#732909") },
                { Base.G, Color.FromHex("#540939") },
                { Base.C, Color.FromHex("#204D07") },
                { Base.Unknown, Color.FromHex("#B81414") },
                { Base.Empty, Color.Transparent }
            };

        public GeneticsConsoleWindow()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);

            BtnSequencing.OnPressed += a => OnSequenceButtonPressed?.Invoke(a);
            BtnActivateGene.OnPressed += a => OnActivateButtonPressed?.Invoke(a);
            BtnCancelActivation.OnPressed += a => OnCancelActivationButtonPressed?.Invoke(a);

            BtnFillAsA.OnPressed += a => SendFillBasePairEvent(a, Base.A);
            BtnFillAsT.OnPressed += a => SendFillBasePairEvent(a, Base.T);
            BtnFillAsG.OnPressed += a => SendFillBasePairEvent(a, Base.G);
            BtnFillAsC.OnPressed += a => SendFillBasePairEvent(a, Base.C);
            BtnFillAsUnkown.OnPressed += a => SendFillBasePairEvent(a, Base.Unknown);

            BtnFillCancel.OnPressed += a => OnCancelFillBasePairButtonPressed(a);

            CTabContainer.SetTabTitle(0, Loc.GetString("genetics-console-ui-window-tab-gene-repair"));
            CTabContainer.SetTabTitle(1, Loc.GetString("genetics-console-ui-window-tab-mutations"));

            MutationTypeHeader.Text = Loc.GetString("genetics-console-ui-window-mutation-type-header");
            MutationBlockHeader.Text = Loc.GetString("genetics-console-ui-window-gene-block-header");
            MutationActivateHeader.Text = Loc.GetString("genetics-console-ui-window-gene-activate-header");

        }

        public void SetGeneDirty()
        {
            _geneDirty = true;
        }

        private string GetGeneTypeLoc(Gene gene, Dictionary<long, string> knownMutations)
        {
            switch (gene.Type)
            {
                case GeneType.Species:
                    return Loc.GetString("genetics-console-ui-window-gene-block-type-species");
                case GeneType.BaseLayer:
                    return Loc.GetString("genetics-console-ui-window-gene-block-type-base-layer");
                case GeneType.SkinColor:
                    return Loc.GetString("genetics-console-ui-window-gene-block-type-skin-color");
                case GeneType.EyeColor:
                    return Loc.GetString("genetics-console-ui-window-gene-block-type-eye-color");
                case GeneType.Markings:
                    return Loc.GetString("genetics-console-ui-window-gene-block-type-marking");
                case GeneType.Sex:
                    return Loc.GetString("genetics-console-ui-window-gene-block-type-sex");
                case GeneType.Mutation:
                    var mutationId = gene.Blocks[0].Value;
                    if (knownMutations.ContainsKey(mutationId)) return knownMutations[mutationId];
                    return Loc.GetString("genetics-console-ui-window-gene-block-type-unknown");
                default:
                    return Loc.GetString("genetics-console-ui-window-gene-block-type-unknown");
            }

        }

        private PanelContainer CreateBoxForBP(BasePair bp, bool top, int blockIndex, int pairIndex)
        {
            Base b = (top) ? bp.TopAssigned : bp.BotAssigned;
            var editable = top && bp.TopActual == Base.Unknown || !top && bp.BotActual == Base.Unknown;
            var container = new PanelContainer
            {
                PanelOverride = new StyleBoxFlat { BackgroundColor = BaseToColor[b] },
                MinSize = BlockSize,
                RectDrawClipMargin = 0,
                HorizontalExpand = true,
                HorizontalAlignment = HAlignment.Stretch
            };
            if (editable)
            {
                var bpButton = new FillBasePairButton(blockIndex, pairIndex, top)
                {
                    Text = PuzzleChecker.BaseToChar[b],
                    MinSize = BlockSize,
                    HorizontalAlignment = HAlignment.Center,
                    HorizontalExpand = false

                };
                container.AddChild(bpButton);
                bpButton.OnPressed += e => OnOpenBasePairModalButton(e, bpButton);
            }
            else
            { 
                container.AddChild(new Label
                {
                    Text = PuzzleChecker.BaseToChar[b],
                    MinSize = BlockSize,
                    HorizontalAlignment = HAlignment.Center,
                    HorizontalExpand = false
                });
            }
            return container;
        }

        private bool ShouldUpdateGenePuzzle(GenePuzzle puzzle)
        {
            if (_geneDirty) return true;
            if (puzzle.UsedBlocks.Count != _prevUsedBlockCnt) return true;
            if (puzzle.UnusedBlocks.Count != _prevUnusedBlockCnt) return true;
            return false;
        }

        public void OnOpenBasePairModalButton(BaseButton.ButtonEventArgs e, FillBasePairButton btn)
        {
            _targetBaseTop = btn.TopOrBottom;
            _targetDNABlockIndex = btn.BlockIndex;
            _targetPairIndex = btn.PairIndex;
            if (!_modalOpen)
            {
                _modalOpen = true;
                ActivationScreenMainBody.Modulate = Color.FromHex("#888888");
                FillInBlockOverlay.MouseFilter = MouseFilterMode.Stop;
                FillInBlockOverlay.Visible = true;
            }
        }
        public void OnCancelFillBasePairButtonPressed(BaseButton.ButtonEventArgs e)
        {
            CloseModal();
        }

        private void CloseModal()
        {
            if (_modalOpen)
            {
                _modalOpen = false;
                ActivationScreenMainBody.Modulate = Color.White;
                FillInBlockOverlay.MouseFilter = MouseFilterMode.Pass;
                FillInBlockOverlay.Visible = false;
                _geneDirty = true;
            }
        }

        public void SendFillBasePairEvent(BaseButton.ButtonEventArgs e, Base newBase)
        {
            var btnEvent = new FillBasePairButtonPressedMessage(newBase, _targetDNABlockIndex, _targetPairIndex, _targetBaseTop);
            OnFillBasePairButtonPressed?.Invoke(e, btnEvent);
            CloseModal();
        }

        public void SetTargetGene(Gene gene, Dictionary<long, string> knownMutations, GenePuzzle? puzzle)
        {
            if (puzzle == null || !ShouldUpdateGenePuzzle(puzzle)) return;

            _prevUsedBlockCnt = puzzle.UsedBlocks.Count;
            _prevUnusedBlockCnt = puzzle.UnusedBlocks.Count;
            _geneDirty = false;

            var geneTypeText = GetGeneTypeLoc(gene, knownMutations);
            ActivationTargetType.Text = Loc.GetString("genetics-console-ui-window-gene-block-type", ("type", geneTypeText));

            BtnActivateGene.Disabled = !PuzzleChecker.CanSubmitPuzzle(puzzle);

            UnusedTargetBlocks.RemoveAllChildren();
            ActivationTargetBlocks.RemoveAllChildren();
            var usedBlockContainer = new BoxContainer
            {
                HorizontalExpand = true
            };
            var unusedBlockContainer = new BoxContainer
            {
                HorizontalExpand = true,

            };
            if (puzzle != null)
            {
                int i = 0;
                foreach (var block in puzzle.UnusedBlocks)
                {
                    var unusedBlockButton = new IndexedButton(i, "");
                    unusedBlockButton.OnPressed += e => OnUnusedBlockButtonPressed?.Invoke(e, unusedBlockButton);
                    var panelContainer = CreatePuzzleBlock(block, i);
                    unusedBlockButton.AddChild(panelContainer);
                    unusedBlockContainer.AddChild(unusedBlockButton);
                    i++;
                }

                int j = 0;
                foreach (var block in puzzle.UsedBlocks)
                {
                    var usedBlockButton = new IndexedButton(j, "");
                    usedBlockButton.OnPressed += e => OnUsedBlockButtonPressed?.Invoke(e, usedBlockButton);
                    var panelContainer = CreatePuzzleBlock(block, i+j);
                    usedBlockButton.AddChild(panelContainer);
                    usedBlockContainer.AddChild(usedBlockButton);
                    j++;
                }
            }
            UnusedTargetBlocks.AddChild(unusedBlockContainer);
            ActivationTargetBlocks.AddChild(usedBlockContainer);
        }

        private PanelContainer CreatePuzzleBlock(List<BasePair> block, int blockIndex)
        {
            var panelContainer = new PanelContainer
            {
                Margin = new Thickness(5, 2),
                PanelOverride = new StyleBoxFlat
                {
                    BackgroundColor = Color.FromHex("#404046"),
                    BorderColor = Color.FromHex("#86868d"),
                    BorderThickness = new Thickness(1)
                }
            };
            var gridContainer = new GridContainer
            {
                Columns = block.Count,
                Rows = 2,
                HSeparationOverride = 2,
                VSeparationOverride = 2
            };

            int i = 0;
            foreach (var pair in block)
            {
                var topBox = CreateBoxForBP(pair, true, blockIndex, i);
                gridContainer.AddChild(topBox);

                var botBox = CreateBoxForBP(pair, false, blockIndex, i);
                gridContainer.AddChild(botBox);
                i++;
            }
            panelContainer.AddChild(gridContainer);
            return panelContainer;
        }

        public void SetGeneRepairPanel(List<GeneDisplay> geneDisplays, Dictionary<long, string> knownMutations)
        {
            if (!_geneDirty) return;
            _geneDirty = false;

            GeneRepairBlocks.RemoveAllChildren();
            MutationBlocks.RemoveAllChildren();
            var index = 0;
            foreach (var geneDisplay in geneDisplays)
            {
                var geneBox = new BoxContainer
                {
                    Orientation = LayoutOrientation.Horizontal,
                    HorizontalExpand = true
                };

                var geneTypeText = GetGeneTypeLoc(geneDisplay.Gene, knownMutations);
                geneBox.AddChild(new Label
                {
                    Text = Loc.GetString("genetics-console-ui-window-gene-block-type", ("type", geneTypeText)),
                    HorizontalExpand = true
                });

                geneBox.AddChild(new Label
                {
                    Text = geneDisplay.Display,
                    HorizontalExpand = true,
                    ClipText = true
                });

                var buttonContainer = new BoxContainer
                {
                    Orientation = LayoutOrientation.Horizontal,
                    HorizontalExpand = true
                };
                geneBox.AddChild(buttonContainer);

                if (geneDisplay.Gene.Damaged)
                {
                    geneBox.Modulate = new Color(255, 0, 0);
                    var repairButton = new IndexedButton(index, Loc.GetString("genetics-console-ui-window-gene-repair-prompt"));
                    repairButton.OnPressed += e => OnRepairButtonPressed?.Invoke(e, repairButton);
                    buttonContainer.AddChild(repairButton);
                }
                GeneRepairBlocks.AddChild(geneBox);

                if(geneDisplay.Gene.Type == GeneType.Mutation)
                {
                    if (!geneDisplay.Gene.Active)
                    {
                        var activateButton = new IndexedButton(index, Loc.GetString("genetics-console-ui-window-gene-activate-prompt"));
                        activateButton.OnPressed += e => OnStartActivationButtonPressed?.Invoke(e, activateButton);
                        buttonContainer.AddChild(activateButton);
                    }
                    else
                    {
                        buttonContainer.AddChild(new Label
                        {
                            Text = Loc.GetString("genetics-console-ui-window-gene-mutation-status-activated"),
                            HorizontalExpand = true
                        });
                    }

                    MutationBlocks.AddChild(geneBox);
                }

                ++index;
            }
        }

        public void SetProgressBarStatus(bool visible, float percentage)
        {
            ProgressBar.Visible = visible;
            ProgressBar.Value = percentage;
        }

        public void SetActiveScreen(GeneticsConsoleScreen screen)
        {
            switch (screen)
            {
                case GeneticsConsoleScreen.Status:
                    IntroScreen.Visible = true;
                    ModificationScreen.Visible = false;
                    ActivationScreen.Visible = false;
                    break;
                case GeneticsConsoleScreen.GeneRepair:
                    IntroScreen.Visible = false;
                    ModificationScreen.Visible = true;
                    ActivationScreen.Visible = false;
                    break;
                case GeneticsConsoleScreen.Activation:
                    IntroScreen.Visible = false;
                    ModificationScreen.Visible = false;
                    ActivationScreen.Visible = true;
                    break;
            }
        }

        public void SetStatusMessage(string msg, bool btnEnabled)
        {
            StatusMessage.Text = msg;
            BtnSequencing.Disabled = !btnEnabled;
        }

        public sealed class FillBasePairButton : Button
        {
            public int BlockIndex { get; }
            public int PairIndex { get; }
            public bool TopOrBottom { get; }
            public FillBasePairButton(int blockIndex, int pairIndex, bool topOrBottom)
            {
                BlockIndex = blockIndex;
                PairIndex = pairIndex;
                TopOrBottom = topOrBottom;
            }
        }
        public sealed class IndexedButton : Button
        {
            public int Index { get; }

            public IndexedButton(int index, string text)
            {
                Index = index;
                Text = text;
            }
        }
    }
}

